# Generated by Django 3.2.7 on 2021-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('category_name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
